### ISSUE TITLE
NuGet Lib Targeting .Net Framework 2.0 instead of .NetStandard

### ISSUE THREAD

**Issue by caesay** [taspeotis/DeltaCompressionDotNet#17]
Despite the current csproj targetting `netstandard1.3`, the current 2.0.0 nuget package is published with the dll's in the `net20` lib folder, which refers to the full ".Net Framework 2.0", and not to dotnet standard. 

This causes errors when referencing the nuget package from a netstandard project. 

> Package 'DeltaCompressionDotNet' was restored using '.NetFramework' instead of the project target framework '.NetStandard'. This package may not be fully compatible with your project.

Suggested Resolution:
- Re-target csproj to `netstandard2.0`
- Publish nuget package with the DeltaCompressionDotNet.dll file in the `lib/netstandard2.0` folder.

https://docs.microsoft.com/en-us/nuget/reference/target-frameworks

**Comment by taspeotis** [comment]
Thanks to [this contribution](https://github.com/taspeotis/DeltaCompressionDotNet/pull/18) this issue is resolved.

NuGet is [indexing a v2.0.1 of DeltaCompressionDotNet](https://www.nuget.org/packages/DeltaCompressionDotNet/2.0.1) that targets:

* .NET Framework 2.0
* .NET Standard 1.3
* .NET Standard 2.0
